# Configuration for Travis CI http://travis-ci.org

# Use container
sudo: false

language: java

# Caching 
cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk6
